gui:
  nerdFontsVersion: 3
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 16
  filterMode: fuzzy
  statusPanelView: allBranchesLog

git:
  mainBranches:
    - master
    - main
    - dev
  autoForwardBranches: allBranches
  branchLogCmd: "git log --graph --color=always --oneline --decorate --date=relative {{branchName}} --"
  allBranchesLogCmds:
    - "git log --graph --color=always --oneline --decorate --date=relative --all"
