gui:
  nerdFontsVersion: 3
  expandFocusedSidePanel: true
  filterMode: fuzzy
  statusPanelView: allBranchesLog

git:
  mainBranches:
    - master
    - main
    - dev
  autoForwardBranches: allBranches
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline {{branchName}} --"
  # branchLogCmd: "log --graph --pretty=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset) %C(auto)%d%C(reset)' --abbrev-commit --date=relative {{branchName}} --"
  allBranchesLogCmds:
    # - "log --graph --pretty=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset) %C(auto)%d%C(reset)' --abbrev-commit --date=relative --all"
    - "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium --oneline"
