keybinding:
  universal:
    quit: <F10>

gui:
  nerdFontsVersion: 3
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 12
  filterMode: fuzzy
  statusPanelView: allBranchesLog
  authorColors:
    "Radamés Vega-Alfaro": "#8d4004"

git:
  mainBranches:
    - master
    - main
    - dev
  autoForwardBranches: allBranches
  branchLogCmd: "git log --graph --color=always --oneline --decorate --date=relative {{branchName}} --"
  allBranchesLogCmds:
    - "git log --graph --color=always --oneline --decorate --date=relative --all"
